name: build-apk

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Buildozer system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            build-essential libssl-dev libffi-dev \
            libsqlite3-dev libjpeg-dev libfreetype6-dev \
            zlib1g-dev

      - name: Download and set up Android SDK
        run: |
          SDK_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
          mkdir -p ${HOME}/android-sdk/cmdline-tools
          curl -o sdk.zip $SDK_URL
          unzip sdk.zip -d ${HOME}/android-sdk/cmdline-tools
          mv ${HOME}/android-sdk/cmdline-tools/cmdline-tools ${HOME}/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=${HOME}/android-sdk" >> $GITHUB_ENV
          echo "${HOME}/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "${HOME}/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Configure SDK and Accept Licenses
        run: |
          yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses
          sdkmanager --sdk_root=${ANDROID_HOME} \
            "platform-tools" \
            "platforms;android-30" \
            "build-tools;30.0.3" \
            "cmdline-tools;latest"

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install cython buildozer

      - name: Build with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/*.apk
