name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Buildozer system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              python3-pip \
              build-essential \
              git \
              python3 \
              python3-venv \
              libsdl2-dev \
              libsdl2-image-dev \
              libsdl2-mixer-dev \
              libsdl2-ttf-dev \
              libportmidi-dev \
              libswscale-dev \
              libavformat-dev \
              libavcodec-dev \
              zlib1g-dev \
              libgstreamer1.0-dev \
              gstreamer1.0-plugins-base \
              gstreamer1.0-plugins-good \
              libzip-dev

      # --- THIS STEP IS NOW CORRECTED ---
      - name: Download and set up Android SDK
        run: |
          SDK_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
          SDK_DIR="$HOME/android-sdk"
          mkdir -p $SDK_DIR
          wget -q $SDK_URL -O android-sdk.zip
          unzip -q android-sdk.zip -d $SDK_DIR
          rm android-sdk.zip
          # Correctly rename the unzipped folder to 'latest' and place it inside 'cmdline-tools'
          mkdir -p $SDK_DIR/cmdline-tools
          mv $SDK_DIR/cmdline-tools $SDK_DIR/cmdline-tools/latest

      - name: Configure SDK and Accept Licenses
        run: |
          SDK_DIR="$HOME/android-sdk"
          echo "PATH=$PATH:$SDK_DIR/cmdline-tools/latest/bin:$SDK_DIR/platform-tools" >> $GITHUB_ENV
          echo "ANDROID_HOME=$SDK_DIR" >> $GITHUB_ENV
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-33"

      - name: Install Buildozer and Cython
        run: |
          pip install buildozer
          pip install cython==0.29.34

      - name: Build with Buildozer
        run: buildozer -v android debug