name: build-android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-17-jdk
        pip install --upgrade pip cython buildozer

    - name: Install Android SDK Build Tools
      run: |
        export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-33" "build-tools;33.0.2"

    - name: Build Debug APK
      run: |
        buildozer android debug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-debug-apk
        path: bin/*.apk
