# In .github/workflows/main.yml

name: Build Kivy APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up Java Development Kit (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Install system dependencies for Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            build-essential \
            git \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            liblzma-dev \
            libbz2-dev \
            libncurses5-dev \
            libsqlite3-dev \
            libreadline-dev \
            llvm \
            pkg-config \
            autoconf \
            libtool \
            unzip

      - name: Install Buildozer and Cython
        run: python -m pip install --upgrade pip buildozer cython

      - name: Set up Android SDK and NDK
        run: |
          # Download and unzip to a temporary directory to avoid the 'mv' conflict
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/android-sdk-temp
          unzip cmdline-tools.zip -d $HOME/android-sdk-temp
          
          # Create the correct final directory structure
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          
          # Move the unzipped contents to the final destination
          mv $HOME/android-sdk-temp/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          
          # Clean up the temporary directory
          rm -rf $HOME/android-sdk-temp
          
          # Set environment variables
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          
          # Manage SDK packages
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "ndk;26.1.10909125"
          
          echo "ANDROID_NDK_HOME=$HOME/android-sdk/ndk/26.1.10909125" >> $GITHUB_ENV

      - name: Run the Buildozer build
        run: buildozer -v android debug

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk