# In .github/workflows/main.yml

name: Build Kivy APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer using docker run
        run: |
          docker run --rm \
            -v "$(pwd)":/home/kivy/project \
            kivy/buildozer:master \
            bash -c "chown -R kivy:kivy . && buildozer -v android debug"

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk